blank_issues_enabled: true
contact_links:
  - name: Submit issues about AperosVoxel
    url: https://github.com/VetusChronos/aperosvoxel/issues/new/choose
    about: Only submit issues of the engine in this repository's issue tracker. Submit those of AperosVoxel in its own issue tracker.
  - name: Search for issue trackers of third-party games
    url: https://content.aperosvoxel.domain/packages/?type=game
    about: For issues of third-party games, search for the game in the ContentDB and then submit an issue in their issue tracker.
